<a href="https://colab.research.google.com/github/sunpochin/colab_notebooks/blob/main/tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Change runtime of notebook to GPU 
      Select Runtime-> Change Runtime type -> select runtime python 3 and hardward accelerator GPU
    


# Install pytorch and torchvision for python 3 and cuda 8.0

In [1]:
!pip3 install https://download.pytorch.org/whl/cu80/torch-1.0.0-cp36-cp36m-linux_x86_64.whl
!pip3 install torchvision

     |████████████████████████████████| 532.5MB 30kB/s 
ERROR: torchvision 0.7.0+cu101 has requirement torch==1.6.0, but you'll have torch 1.0.0 which is incompatible.
  Found existing installation: torch 1.6.0+cu101
    Uninstalling torch-1.6.0+cu101:
      Successfully uninstalled torch-1.6.0+cu101
     |████████████████████████████████| 748.8MB 22kB/s 
  Found existing installation: torch 1.0.0
    Uninstalling torch-1.0.0:
      Successfully uninstalled torch-1.0.0


In [2]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [3]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[5.5803e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 2.0168e-36]])


Construct a randomly initialized matrix:



In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7732, 0.8532, 0.8273],
        [0.8131, 0.5196, 0.5206],
        [0.6099, 0.8854, 0.9001],
        [0.4325, 0.1800, 0.7373],
        [0.1704, 0.0461, 0.2508]])


Construct a matrix filled zeros and of dtype long:



In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1464, -0.9868,  0.9781],
        [ 1.6438, -0.8984, -0.6159],
        [-1.7074, -0.1676,  1.0812],
        [ 0.2561, -1.0254, -2.1710],
        [ 0.2411,  1.3726, -1.0745]])


Get its size:



In [9]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.7811, -0.5677,  1.4350],
        [ 1.8709, -0.5893, -0.4359],
        [-1.6190,  0.5519,  1.3821],
        [ 1.2337, -0.6216, -1.2487],
        [ 0.3626,  1.8130, -0.4120]])


Addition: syntax 2



In [11]:
print(torch.add(x, y))

tensor([[ 0.7811, -0.5677,  1.4350],
        [ 1.8709, -0.5893, -0.4359],
        [-1.6190,  0.5519,  1.3821],
        [ 1.2337, -0.6216, -1.2487],
        [ 0.3626,  1.8130, -0.4120]])


Addition: providing an output tensor as argument



In [12]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.7811, -0.5677,  1.4350],
        [ 1.8709, -0.5893, -0.4359],
        [-1.6190,  0.5519,  1.3821],
        [ 1.2337, -0.6216, -1.2487],
        [ 0.3626,  1.8130, -0.4120]])


Addition: in-place



In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.7811, -0.5677,  1.4350],
        [ 1.8709, -0.5893, -0.4359],
        [-1.6190,  0.5519,  1.3821],
        [ 1.2337, -0.6216, -1.2487],
        [ 0.3626,  1.8130, -0.4120]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [14]:
print(x[:, 1])

tensor([-0.9868, -0.8984, -0.1676, -1.0254,  1.3726])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.1323])
-1.1322948932647705


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [21]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!